/obj/item/spellbook/proc/get_theme_flavor(form)
	switch(form)
		if(FORM_FIRE)
			return list("aflame", "Faint heat radiates from its pages, and its runes are all subtly singed.")
		if(FORM_ICE)
			return list("frostbound", "Its pages are cool to the touch, rimed with a frost that never quite melts.")
		if(FORM_LIGHTNING)
			return list("storm-charged", "Tiny sparks crawl between its runes whenever the cover is opened.")
		if(FORM_EARTH)
			return list("stoneveined", "Its binding is threaded with fine mineral veins, heavy as river stone.")
		if(FORM_ARCANE)
			return list("thrice-warded", "Its script folds in on itself in ways the eye struggles to follow.")
		if(FORM_DEATH)
			return list("grave-touched", "A faint chill of the grave lingers about its pages.")
		if(FORM_LIFE)
			return list("verdant", "Its margins are traced with fine, living green filigree.")
		if(FORM_AIR)
			return list("windswept", "Its pages riffle gently even in still air.")
		if(FORM_WATER)
			return list("tidebound", "Condensation beads along its cover no matter how dry the room.")
	return list(null, null)
